title: K-Management Limited
description: Strategic consultancy, investor startup assessment, and selective angel investment for ecommerce and IT services.
baseurl: ""
url: "https://www.k-management.com.hk"
markdown: kramdown
plugins: []
