title: K-Management Limited
description: Strategic consultancy, investor startup assessment, and selective angel investment for ecommerce and IT services.
baseurl: "/website"
url: "https://k-management.github.io"
markdown: kramdown
plugins: []
